services:
  - type: web
    name: football-league-backend
    env: node
    plan: free
    buildCommand: |
      cd backend
      npm install
      npm run build
    startCommand: |
      cd backend
      npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: USE_POSTGRES
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: PGSSLMODE
        value: require
      # Ниже — опционально, если хочешь экспорт/чтение из Sheets
      - key: GOOGLE_SHEETS_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
    healthCheckPath: /health

  - type: web
    env: static
    name: football-league-frontend
    buildCommand: |
      cd frontend
      npm install
      npm run build
    publishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: football-league-backend
          envVarKey: RENDER_EXTERNAL_URL
